1st task
js-tasks-ru/jsbasic-20221028_sema0517 pull request #1
Opened 2022-10-29 18:27 UTC by sema0517

Function sum implementation

2022-10-29 18:27 UTC, jsru commented
Спасибо за отправленный пулриквест, теперь @koalex должен запустить тесты.

2022-10-31 04:56 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-10-31 04:58 UTC, koalex requested changes
Нужно решить **1-1**

2022-10-31 19:35 UTC, sema0517 commented
> Нужно решить **1-1**

Константин, добавил решение задачи 1-1

2022-11-03 07:21 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2022-11-03 07:21 UTC, koalex approved these changes

2022-11-03 07:22 UTC, merged